version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:lts
      - image: circleci/php:7.2
    steps:
      - checkout
      - run:
          name: install
          command: yarn install
      - run:
          name: prod
          command: yarn prod
