name: Build

on: [push, pull_request]

jobs:
    build:
        runs-on: ubuntu-latest
        defaults:
            run:
                shell: bash

        steps:
            - uses: actions/checkout@v2

            - name: Build
              run: |
                  yarn
                  yarn deploy

            - name: Deploy to Vercel
              uses: amondnet/now-deployment@v2
              with:
                  zeit-token: ${{ secrets.ZEIT_TOKEN }}
                  now-args: '--confirm'
