name: 'Deploy'

on:
    schedule:
        - cron: '0 12 * * *' # At noon every day

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v2
          - uses: amondnet/now-deployment@v2
            with:
              zeit-token: ${{ secrets.ZEIT_TOKEN }} # Required
