name: Build

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    build:
        if: "!contains(github.event.commits[0].message, 'skip ci')"
        runs-on: ubuntu-latest
        defaults:
            run:
                shell: bash

        steps:
            - uses: actions/checkout@v2

            - name: Build
              run: |
                  yarn
                  yarn deploy

            - name: Push to master
              run: |
                  git config --global user.email "scriptex.bg@gmail.com"
                  git config --global user.name "Atanas Atanasov"
                  git add -A && git commit -m "[Automated] Build html file from php files"
                  git push --force -u origin master
